### ISSUE TITLE
imperial length toBest can return nautical miles (nMi)

### ISSUE THREAD

**Issue by davetapley** [convert-units/convert-units#246] opened 2022-07-01 00:48 UTC
If I do:

```ts
convert(3670).from("m").toBest({ system: "imperial" })
```

I get a result of `1.981641` nautical miles (`nMi`) and not `2.280432` miles (`mi`).
I'll admit that is _technically_ correct per: https://github.com/convert-units/convert-units/blob/af0dc8d0e03cadc6e6134dd00cb71aa83ced559d/README.md?plain=1#L72

... but probably isn't what most people want 🙈 

---

Adding `exclude: ["nMi"]` is a workaround, but perhaps `nautical` should be considered its own system? ⚓

**Comment by Taar** [comment] 2022-07-04 20:06
Using `exclude: ["nMi"]` is the correct way to handle this situation. The other solution is creating a custom measure that only contains the units needed.

**Comment by davetapley** [comment] 2022-07-13 17:52
I agree it `exclude` is correct in library's current state, but I'd argue it's not obvious that `nMi` should be in `imperial`, both from a practical and theoretical stand point:

**Practically:**

1. I _assume_ using metric internally and then `toBest({ system: "imperial" })` is a fairly common use case

2. I _assume_ a tiny fraction of people would actually want nautical miles as a `toBest` type
  (and even then, they'd probably be explicit about it, since you wouldn't want a mix of `mi` and `nMi`)
  
    @webmasterkai are you using `toBest`, how do you feel about this?


**Theoretically:**

On Wikipedia nautical miles unit system is given as "Non-SI unit", where as miles are "British imperial/US customary". 
They are listed on the [imperial units page](https://en.wikipedia.org/wiki/Imperial_units) but under a **Maritime units** sub-table.

---

@Taar would you be open to removing `nMi` from `imperial` to e.g. `maritime` if it catches other people out?

**Comment by Taar** [comment] 2022-07-15 14:55
So the issue isn't `toBest` but rather that there is an unexpected unit in the `imperial` system? If that's the case, could we close this issue and open a different issue to discuss the state of the measures?

**Closed** 2023-02-02 18:25 UTC
